use_frameworks!

platform :ios, '9.0'

target '${POD_NAME}_Example' do
  pod '${POD_NAME}', :path => '../'
  ${Pod_Protocol}

  pod 'Masonry'
  pod 'MJExtension'

  target '${POD_NAME}_Tests' do
    inherit! :search_paths

    ${INCLUDED_PODS}
  end
end
